### ISSUE TITLE
Should it put a backslash in front of "&" and "$" in a title?

### ISSUE THREAD

**Issue by blueskyson** [karlosos/getbibtex#3]
This tool is really great! But I noticed a little thing. When I generated a citation of https://hedera.com/blog/analysis-remediation-of-the-precompile-attack-on-the-hedera-network, the result was:
```bibtex
@misc{hederaAnalysisRemediation,
	author = {},
	title = {{A}nalysis & {R}emediation of the {P}recompile {A}ttack on the… | {H}edera --- hedera.com},
	howpublished = {\url{https://hedera.com/blog/analysis-remediation-of-the-precompile-attack-on-the-hedera-network}},
	year = {},
	note = {[Accessed 15-10-2023]},
}
```

The Overleaf compiler argued that:
> You have placed an alignment tab character '&' in the wrong place. If you want to align something, you must write it inside an align environment such as \begin{align} … \end{align}, \begin{tabular} … \end{tabular}, etc. If you want to write an ampersand '&' in text, you must write \& instead.

After I change it to `\&`, it's fine now.

**Comment by karlosos** [comment]
@blueskyson thanks for the input. It should be fixed now.
