### ISSUE TITLE
add escaping of underscores

### ISSUE THREAD

**Issue by Radiirgummii** [karlosos/getbibtex#7]
Hi there, awesome project
i have discovered a bug.
If the title of the link contain a underscore it still present in the final output.
my latex environment thought i wanted to use math mode
in my bib. i realy dont know my way around frontend so sorry i cant do it myself. 
i fixed it by just escaping the underscore with a backslash manually. 
I would think underscores arent the only chars that behave that way but i cant test it
thank you for your time.

**Comment by Radiirgummii** [comment]
i have looked around in the codebase and apparantly there already was a simmilar problem with the $ and & chars so i fixed it myself [PR](https://github.com/karlosos/getbibtex/pull/8) is opened

**Comment by karlosos** [comment]
Thanks for your contribution! The PR was merged.
